
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eieyxnstpuwppmtwvvaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZXl4bnN0cHV3cHBtdHd2dmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODA2NDIsImV4cCI6MjA2MTM1NjY0Mn0.erLGN_bIlIGCosAyuBl9ZeUAv7dKVf56m0GJSMREess";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
